---
name: goreleaser

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: coredns/coredns
          ref: v1.8.6
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
