---
name: goreleaser

on:
  push:

jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout CoreDNS
        uses: actions/checkout@v2
        with:
          repository: coredns/coredns
          ref: v1.8.6
      - uses: actions/checkout@v2
        with:
          path: opnsense-coredns-plugins
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: cp opnsense-coredns-plugins/.goreleaser.yml .goreleaser.yml
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --skip-validate --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
